[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
mint-vault = "6VVXJ3hHsXn8kFqCWRPT6VeigbGkcHkUZhhopritHdMi"
swap = "xnrMV3UCFqDefZW3oEY4QGVX8fFmopJGETwWDSfCiUd"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
mint = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
swap = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"